export interface Member {
  id: string;
  name: string;
  country: string;
  city: string;
  email: string;
  occupation: string;
  company: string;
  social: string;
  photoDriveId?: string;
  image?: string;
  chapter: string;
  isLeadership?: boolean;
  roleBadge?: string;
}

export const members: Member[] = [
  {
    id: "m-1",
    name: "Ericka Otero",
    country: "Panamá",
    city: "Ciudad de Panamá",
    email: "pbslatam@pinkbootssociety.org",
    occupation: "Co-Fundadora de Salsipuedes Brewing Co. Encargada de Producción y Control de Calidad. Jueza World Beer Cup 2026.",
    company: "Salsipuedes Brewing Co.",
    social: "@salsipuedesbrewingco @eriquitalamasbonita",
    image: "/members/ericka.jpg",
    chapter: "Pink Boots Latam",
    isLeadership: true,
    roleBadge: "Co-Fundadora & Regional Leader",
  },
  {
    id: "m-2",
    name: "Silvia De Tomas Ayllon",
    country: "Perú",
    city: "Lima",
    email: "silviadetomasa@gmail.com",
    occupation: "Head Brewer y Biersommelier. Jueza World Beer Cup 2026. Co-líder de Pink Boots Latinoamérica.",
    company: "Cervecería Two Broders / Cebichela",
    social: "@Silviadetomas @TwoBroders.pe @Cebichela",
    image: "/members/silvia-de-tomas.jpg",
    chapter: "Perú",
    isLeadership: true,
    roleBadge: "Co-Líder Latam & Head Brewer",
  },
  {
    id: "m-3",
    name: "Keishla Torres",
    country: "Puerto Rico",
    city: "San Juan / Guaynabo",
    email: "jevascerveceras@gmail.com",
    occupation: "Líder Regional de Pink Boots Society LATAM Puerto Rico y Fundadora de Jevas Cerveceras. Mercadeo digital y coordinación de eventos.",
    company: "Jevas Cerveceras",
    social: "@jevascerveceras",
    chapter: "Pink Boots Latam / Puerto Rico",
    isLeadership: true,
    roleBadge: "Líder Sub-Capítulo Puerto Rico",
  },
  {
    id: "m-4",
    name: "Viviana López Gutiérrez",
    country: "México",
    city: "Cuernavaca",
    email: "restaurandoando@gmail.com",
    occupation: "Control de Calidad, Marketing e investigación histórica cervecera.",
    company: "Tebana Laboratorio Cervecero",
    social: "https://www.instagram.com/tebana_laboratorio_cervecero/",
    image: "/members/viviana-lopez.jpg",
    chapter: "México",
    isLeadership: true,
    roleBadge: "Líder de comunidad México",
  },
  {
    id: "m-5",
    name: "Verónica Carrasco",
    country: "Chile",
    city: "Santiago",
    email: "cervezasvericcio@gmail.com",
    occupation: "Maestra cervecera y fundadora.",
    company: "Cervezas Vericcio",
    social: "@cervezavericcio",
    image: "/members/veronica-carrasco.jpg",
    chapter: "Chile",
    isLeadership: true,
    roleBadge: "Maestra Cervecera",
  },
  {
    id: "m-6",
    name: "Fernanda Santos da Costa",
    country: "Brasil",
    city: "Curitiba",
    email: "fernandadacosta@gmail.com",
    occupation: "Sommelieria, enseñanza y turismo cervecero.",
    company: "Cerviajona",
    social: "@nandadacosta008 @cerviajona",
    image: "/members/fernanda-da-costa.jpg",
    chapter: "Brasil",
    isLeadership: true,
    roleBadge: "Sommelier & Referente Brasil",
  },
  {
    id: "m-7",
    name: "Vanjga Vera Loncharich",
    country: "Perú",
    city: "Lima",
    email: "Vanjgavalenka@gmail.com",
    occupation: "Head Brewer, catas y administración cervecera.",
    company: "Cervecería Limamanta",
    social: "@vanjgabeer",
    image: "/members/vanjga-vera.jpg",
    chapter: "Perú",
    roleBadge: "Head Brewer",
  },
  {
    id: "m-8",
    name: "Daniela Jiménez",
    country: "Costa Rica",
    city: "San José",
    email: "jossda2697@gmail.com",
    occupation: "Brewer and Brewing Quality Master.",
    company: "Brevora Brewing and Coffee",
    social: "@brevora.cr",
    image: "/members/daniela-jimenez.jpg",
    chapter: "Costa Rica",
    roleBadge: "Brewer & Quality Master",
  },
  {
    id: "m-9",
    name: "Cynthia Hurtado",
    country: "México",
    city: "Mexicali, Baja California",
    email: "cynthiahurtados@gmail.com",
    occupation: "Juez BJCP, creadora de contenido y administradora de la Asociación de Microcerveceros de Mexicali.",
    company: "Gobierno del Estado de BC / Asoc. de Micro Cerveceros de Mexicali",
    social: "@_beer.me",
    image: "/members/cynthia.jpg",
    chapter: "México",
    roleBadge: "Juez BJCP & Contenido",
  },
  {
    id: "m-10",
    name: "Mariana Guerrero",
    country: "Venezuela",
    city: "",
    email: "marianaguerrerob@gmail.com",
    occupation: "Manager de Calidad en Cervecería.",
    company: "Turk's Head Brewery / Provo Beverages",
    social: "@beerwarrior_ok",
    image: "/members/mariana-guerrero.jpg",
    chapter: "Venezuela",
    roleBadge: "Quality Manager",
  },
  {
    id: "m-11",
    name: "Zitamar Valentine",
    country: "Panamá",
    city: "Ciudad de Panamá",
    email: "valentine.brewingco@gmail.com",
    occupation: "Elaboración y desarrollo de cerveza artesanal.",
    company: "Valentine Brewing Project",
    social: "",
    image: "/members/zitamar-valentine.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Cervecera Artesanal",
  },
  {
    id: "m-12",
    name: "Daiana Milón Mayer",
    country: "Perú",
    city: "Lima",
    email: "dmilon@blackwhiskey.com",
    occupation: "Control de calidad, desarrollo de producto y blending de bebidas destiladas y añejas.",
    company: "Don Michael SAC (Black Whiskey)",
    social: "donmichael.pe",
    image: "/members/daiana.jpg",
    chapter: "Perú",
    roleBadge: "Master Blender & Calidad",
  },
  {
    id: "m-13",
    name: "Eloisa Sanjur",
    country: "Panamá",
    city: "Ciudad de Panamá",
    email: "eloisadelcarmen00@gmail.com",
    occupation: "Brewer en Salsipuedes Brewing Co.",
    company: "Salsipuedes Brewing Co.",
    social: "@eloisa_sanjur",
    image: "/members/eloisa-sanjur.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Brewer",
  },
  {
    id: "m-14",
    name: "Jalen N. Muñoz Carrillo",
    country: "Puerto Rico",
    city: "San Juan",
    email: "jalenart012@gmail.com",
    occupation: "Consumidora apasionada y estudiante de arquitectura en la UPR Río Piedras.",
    company: "UPR Recinto de Río Piedras",
    social: "@j.artgallery_ @jalen.nicoleeee",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Comunidad Cervecera",
  },
  {
    id: "m-15",
    name: "Andrea Zalapa Morfín",
    country: "México",
    city: "",
    email: "andreazalapa@gmail.com",
    occupation: "Maestra cervecera.",
    company: "La Amargura",
    social: "@cerveza_laamargura @andreazmor",
    image: "/members/andrea-zalapa.jpg",
    chapter: "México",
    roleBadge: "Maestra Cervecera",
  },
  {
    id: "m-16",
    name: "Shairai L. Rivera Ramírez",
    country: "Puerto Rico",
    city: "San Juan",
    email: "shairai@gmail.com",
    occupation: "Mercadeo y manejo de redes sociales para restaurantes y barras, apoyando la promoción cervecera y gastronómica.",
    company: "Shynomadpr",
    social: "Shynomadpr",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Marketing & Redes",
  },
  {
    id: "m-17",
    name: "Alexia Medina",
    country: "Panamá",
    city: "Penonomé",
    email: "alemedina19@gmail.com",
    occupation: "Elaboración de cerveza artesanal en comunidad cervecera.",
    company: "Hobby Cerveceros Penonomé",
    social: "@cerveceros_penonome",
    image: "/members/alexia-medina.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Cervecera Artesanal",
  },
  {
    id: "m-18",
    name: "Deborah Rodríguez Mercado",
    country: "Puerto Rico",
    city: "Cayey",
    email: "Adredecayey@gmail.com",
    occupation: "Propietaria de Taberna Cervecera.",
    company: "Adrede, Taberna Cervecera",
    social: "@adredecayey @debbiebee25",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Propietaria Taberna",
  },
  {
    id: "m-19",
    name: "Alexandra Mercado Correa",
    country: "Puerto Rico",
    city: "",
    email: "thegrowlerlady@gmail.com",
    occupation: "Gerente de operaciones, directora creativa y asistente de brewer. Presidenta 2026 Homebrewers PR.",
    company: "La Esquinita Jardín Cervecero & Brewhouse",
    social: "@thegrowlerlady",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Operaciones & Homebrewers PR",
  },
  {
    id: "m-20",
    name: "Mariela Vázquez Chontales",
    country: "México",
    city: "Ensenada, Baja California",
    email: "marielachontales@gmail.com",
    occupation: "Head Brewer en Zirkel Brewing Labs.",
    company: "Zirkel Brewing Labs",
    social: "https://www.instagram.com/zirkel_bl",
    image: "/members/mariela-vazquez.jpg",
    chapter: "México",
    roleBadge: "Head Brewer",
  },
  {
    id: "m-21",
    name: "Cristina Palma",
    country: "El Salvador",
    city: "San Salvador",
    email: "durancristina637@gmail.com",
    occupation: "Producción y Control de Calidad.",
    company: "Cadejo Brewing Company",
    social: "",
    image: "/members/cristina-palma.jpg",
    chapter: "El Salvador",
    roleBadge: "Producción & Calidad",
  },
  {
    id: "m-22",
    name: "Galaxis Ardila",
    country: "Panamá",
    city: "Ciudad de Panamá",
    email: "ardilagala2@gmail.com",
    occupation: "Sommelier de Cervezas y Consultoría.",
    company: "Galabrew",
    social: "@ardilagala",
    image: "/members/galaxis-ardila.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Biersommelier & Consultoría",
  },
  {
    id: "m-23",
    name: "Carla Roa",
    country: "Venezuela",
    city: "San Cristóbal",
    email: "carlaroac@gmail.com",
    occupation: "Logística, diseño de imagen y creadora de su propia línea cervecera.",
    company: "Cerveza Barba Negra",
    social: "@lupulita_ @carlarie",
    image: "/members/carla-roa.jpg",
    chapter: "Venezuela",
    roleBadge: "Diseño & Creadora Cervecera",
  },
  {
    id: "m-24",
    name: "Analía Etcheverrito (Ani Etche)",
    country: "Argentina",
    city: "Caseros, Buenos Aires",
    email: "abetcheverrito@gmail.com",
    occupation: "Responsable de gestión de calidad, jueza de cervezas BJCP y productora de kombucha.",
    company: "Cervecería Ortúzar",
    social: "@anietche",
    image: "/members/analia-etcheverrito.jpg",
    chapter: "Argentina",
    roleBadge: "Gestión Calidad & Jueza BJCP",
  },
  {
    id: "m-25",
    name: "Nathaly Arriaza",
    country: "Guatemala",
    city: "Tecpán",
    email: "Arriaza.nathy89@gmail.com",
    occupation: "Productora de cerveza e hidromiel, co-fundadora de Cervecería Artesanal Iximché.",
    company: "Cervecería Artesanal Iximché",
    social: "@arriaza.nath @iximchela",
    image: "/members/nathaly-arriaza.jpg",
    chapter: "Guatemala",
    roleBadge: "Co-Fundadora & Productora",
  },
  {
    id: "m-26",
    name: "Sandra E. Rodríguez Roldán",
    country: "Puerto Rico",
    city: "Río Grande",
    email: "brew.taller@gmail.com",
    occupation: "Co-dueña y administradora de cervecería y taproom.",
    company: "Brew!!! Taller Experimental / DragonStone Abbey",
    social: "Brew!!! Taller Experimental",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Co-Dueña & Taproom",
  },
  {
    id: "m-27",
    name: "Jessica Rodríguez",
    country: "Puerto Rico",
    city: "Luquillo",
    email: "jessicarodrig32@hotmail.com",
    occupation: "Bióloga y consultora de calidad y asuntos regulatorios. Aficionada y estudiante cervecera.",
    company: "Consultora de Calidad",
    social: "https://www.instagram.com/_the_life_of_jesse_",
    image: "/members/jessica-rodriguez.jpg",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Bióloga & Calidad Regulatoria",
  },
  {
    id: "m-28",
    name: "Elizabeth Karina Ibarra Carvajal",
    country: "Chile",
    city: "",
    email: "karibarra76@gmail.com",
    occupation: "Elaboración de hidromieles, kombuchas y sidras.",
    company: "Experifermentos Ankuru",
    social: "@karinaibarracarvajal @experifermentosankuru",
    image: "/members/karina-ibarra.jpg",
    chapter: "Chile",
    roleBadge: "Productora de Fermentos",
  },
  {
    id: "m-29",
    name: "Nikole Negrón",
    country: "Puerto Rico",
    city: "Aguadilla",
    email: "nikole0623@gmail.com",
    occupation: "Socia de Boxlab Brewing Co / The Beer Box. Gerente General. Becaria Pink Boots.",
    company: "Boxlab Brewing Co. / The Beer Box",
    social: "@Nikoleneg",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Socia & Gerente General",
  },
  {
    id: "m-30",
    name: "Juliehana Carrillo",
    country: "Estados Unidos",
    city: "",
    email: "bolacervecera@gmail.com",
    occupation: "Consumidora, creadora de contenido y defensora de la comunidad cervecera latina.",
    company: "Lúpulos y Melaninapr",
    social: "@Lupulos_y_Melaninapr",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Contenido & Comunidad",
  },
  {
    id: "m-31",
    name: "Angélica M. Adorno Santos",
    country: "Puerto Rico",
    city: "San Juan",
    email: "adornoangelica18@gmail.com",
    occupation: "Cervecera casera y divulgadora.",
    company: "Artesana Cervecera",
    social: "@artesanacervecera",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Homebrewer",
  },
  {
    id: "m-32",
    name: "Zarati Tejeira Fernández",
    country: "Panamá",
    city: "Penonomé",
    email: "ztejeiraf@gmail.com",
    occupation: "Elaboración de Cerveza Artesanal.",
    company: "Cerveceros Penonomé",
    social: "@zaratitejeirafernandez",
    image: "/members/zarati-tejeira.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Cervecera Artesanal",
  },
  {
    id: "m-33",
    name: "Alejandra Dimas",
    country: "México",
    city: "San Luis Potosí",
    email: "aledimas224@gmail.com",
    occupation: "Juez de hidromiel, cerveza y kombucha; productora.",
    company: "Ale Dimas Juez",
    social: "@aledimas.coach",
    image: "/members/ale-dimas.jpg",
    chapter: "México",
    roleBadge: "Juez Cerveza & Fermentos",
  },
  {
    id: "m-34",
    name: "Karen Valderrama",
    country: "Puerto Rico",
    city: "",
    email: "kv@oceanlabbrewing.com",
    occupation: "Coordinadora de Operaciones en Cervecería.",
    company: "Ocean Lab Brewing Co.",
    social: "@kpatriciavt",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Operaciones Cervecera",
  },
  {
    id: "m-35",
    name: "Julieta Batista Jordán",
    country: "Panamá",
    city: "Ciudad de Panamá",
    email: "julieta.batistajj@gmail.com",
    occupation: "Aseguramiento de la Calidad en Cervecería.",
    company: "Cervecería La Rana Dorada",
    social: "@Juliet.labtqim",
    chapter: "Pink Boots Latam",
    roleBadge: "Aseguramiento Calidad",
  },
  {
    id: "m-36",
    name: "Nilda Escobar",
    country: "Puerto Rico",
    city: "Río Grande",
    email: "etapasne@gmail.com",
    occupation: "Promoción y administración de taproom cervecero.",
    company: "Brew Taller Experimental",
    social: "Nilda Escobar",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Administración Taproom",
  },
  {
    id: "m-37",
    name: "Minelis Méndez Vargas",
    country: "Puerto Rico",
    city: "San Juan",
    email: "minelis.mendez.vargas@gmail.com",
    occupation: "Embajadora de marcas, ventas y mercadeo cervecero. Becaria Pink Boots.",
    company: "Vorágine",
    social: "@voragine_",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Ventas & Embajadora",
  },
  {
    id: "m-38",
    name: "Karina M. Vega Escobar",
    country: "Puerto Rico",
    city: "Río Grande",
    email: "k.vegaescobar@gmail.com",
    occupation: "Química Industrial, administración de taproom y asistente en la producción de cervezas artesanales.",
    company: "Dragon Stone / Brew Taller",
    social: "https://www.linkedin.com/in/karina-v-050227188",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Química & Producción",
  },
  // Additional community members with verified photos from the shared community drive
  {
    id: "m-39",
    name: "Adriana",
    country: "Perú",
    city: "Lima",
    email: "",
    occupation: "Integrante y cervecera de la red Pink Boots Society.",
    company: "Pink Boots Latam",
    social: "",
    image: "/members/adriana.jpg",
    chapter: "Perú",
    roleBadge: "Integrante de la Red",
  },
  {
    id: "m-40",
    name: "Ariana",
    country: "Latinoamérica",
    city: "",
    email: "",
    occupation: "Profesional cervecera e integrante activa.",
    company: "Pink Boots Latam",
    social: "",
    image: "/members/ariana.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Comunidad Cervecera",
  },
  {
    id: "m-41",
    name: "Daniela Pareja Mejía",
    country: "Perú",
    city: "Lima",
    email: "",
    occupation: "Integrante y profesional cervecera en la red peruana.",
    company: "Pink Boots Perú",
    social: "",
    image: "/members/daniela-pareja.jpg",
    chapter: "Perú",
    roleBadge: "Comunidad Cervecera",
  },
  {
    id: "m-42",
    name: "Diana Juárez Durán",
    country: "México",
    city: "",
    email: "",
    occupation: "Cervecera artesanal y miembro de la red en México.",
    company: "Pink Boots México",
    social: "",
    image: "/members/diana-juarez-duran.jpg",
    chapter: "México",
    roleBadge: "Cervecera",
  },
  {
    id: "m-43",
    name: "Jary Rocha",
    country: "Latinoamérica",
    city: "",
    email: "",
    occupation: "Profesional y defensora de la inclusión en bebidas fermentadas.",
    company: "Pink Boots Latam",
    social: "",
    image: "/members/jary-rocha.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Comunidad Cervecera",
  },
  {
    id: "m-44",
    name: "Lucía Álvarez",
    country: "Latinoamérica",
    city: "",
    email: "",
    occupation: "Integrante de la comunidad cervecera latinoamericana.",
    company: "Pink Boots Latam",
    social: "",
    image: "/members/lucia-alvarez.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Comunidad Cervecera",
  },
  {
    id: "m-45",
    name: "Noella Candanedo",
    country: "Panamá",
    city: "Ciudad de Panamá",
    email: "",
    occupation: "Profesional cervecera e integrante de la red regional.",
    company: "Pink Boots Latam",
    social: "",
    image: "/members/noella-candanedo.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Comunidad Cervecera",
  },
  {
    id: "m-46",
    name: "Rossemary Álvarez",
    country: "Latinoamérica",
    city: "",
    email: "",
    occupation: "Integrante activa de Pink Boots Society Latin America.",
    company: "Pink Boots Latam",
    social: "",
    image: "/members/rossemary-alvarez.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Comunidad Cervecera",
  },
  {
    id: "m-47",
    name: "Valeria Mena",
    country: "Latinoamérica",
    city: "",
    email: "",
    occupation: "Profesional cervecera y entusiasta de la fermentación.",
    company: "Pink Boots Latam",
    social: "",
    image: "/members/valeria-mena.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Comunidad Cervecera",
  },
  {
    id: "m-48",
    name: "Vivian López Gonzales",
    country: "Latinoamérica",
    city: "",
    email: "",
    occupation: "Miembro de la red cervecera latinoamericana.",
    company: "Pink Boots Latam",
    social: "",
    image: "/members/vivian-lopez-gonzales.jpg",
    chapter: "Pink Boots Latam",
    roleBadge: "Comunidad Cervecera",
  },
  {
    id: "m-49",
    name: "Zadkiela",
    country: "Puerto Rico",
    city: "San Juan",
    email: "",
    occupation: "Integrante del sub-capítulo de Puerto Rico.",
    company: "Pink Boots Latam / Puerto Rico",
    social: "",
    image: "/members/zadkiela.jpg",
    chapter: "Pink Boots Latam / Puerto Rico",
    roleBadge: "Comunidad Cervecera",
  },
];

export const allCountries = [
  "Todos",
  "Puerto Rico",
  "Panamá",
  "México",
  "Perú",
  "Chile",
  "Venezuela",
  "Argentina",
  "Brasil",
  "Costa Rica",
  "El Salvador",
  "Guatemala",
] as const;

export function getMembersByCountry(country: string): Member[] {
  if (!country || country === "Todos") return members;
  return members.filter((m) => m.country.toLowerCase() === country.toLowerCase());
}

/**
 * Members that have a photo ready for the Community Collage
 */
export const collageMembers: Member[] = members.filter((m) => Boolean(m.image));
